# Generated by Django 6.0.2 on 2026-02-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='monthly_sales',
            field=models.IntegerField(default=0),
        ),
    ]
